[Interface]
# Name = laptop.example-vpn.dev
Address = 172.19.7.2
PrivateKey = sIo/3ri1suLCDaaPbPK5azq3AokYYNjgUuUwA6KPIlk=
#DNS = 1.1.1.1
ListenPort = 52218
[Peer]
# Name = server.example-vpn.tld
Endpoint = 37.156.147.42:56628
PublicKey = 3tyctDDHbJkc/ZgiZ/+vMgrleZyeAKwNZkzhDVGKXi0=  #Paste PFsense Publickey to Ubuntu Peers
#aAllowedIPs = 0.0.0.0/0
AllowedIPs = 172.19.7.0/24
PersistentKeepalive = 25
