[Interface]
# Name = laptop.example-vpn.dev
Address = 172.19.6.2
PrivateKey = iNAiwdqggwxuYMVuVP8dXM5Ka7T7ZX0zwoveBVbYXWQ=
#DNS = 1.1.1.1
ListenPort = 52217
[Peer]
# Name = server.example-vpn.tld
Endpoint = 37.156.147.42:56627
PublicKey = pNCHRWmCdR7+KadjskNttYNry+Ngbhl+gqZSbia7XBQ=    #Paste PFsense Publickey to Ubuntu Peers
#aAllowedIPs = 0.0.0.0/0
AllowedIPs = 172.19.6.0/24
PersistentKeepalive = 25
