# gr-p3
[Interface]
Address = 172.19.2.2
PrivateKey = oBTWmRtbL8JIpaRDpm3lXXmO3aR+Uy50GF/agWExPmg=
ListenPort = 52226

[Peer]
Endpoint = 37.156.147.42:56683
PublicKey = ISzb7vSNONZ1davsvS2NSf7YHJdN09tAKCIKcp2h1hc=
AllowedIPs = 172.19.2.0/24
PersistentKeepalive = 25
