[Interface]
# Name = laptop.example-vpn.dev
Address = 172.19.2.2
PrivateKey = oBTWmRtbL8JIpaRDpm3lXXmO3aR+Uy50GF/agWExPmg=
#DNS = 1.1.1.1
ListenPort = 52226
[Peer]
# Name = server.example-vpn.tld
Endpoint = 37.156.147.42:56683
PublicKey = ISzb7vSNONZ1davsvS2NSf7YHJdN09tAKCIKcp2h1hc=    #Paste PFsense Publickey to Ubuntu Peers
#aAllowedIPs = 0.0.0.0/0
AllowedIPs = 172.19.2.0/24
PersistentKeepalive = 25
