[Interface]
# Name = laptop.example-vpn.dev
Address = 172.19.22.2
PrivateKey = 
#DNS = 1.1.1.1
ListenPort = 52242
[Peer]
# Name = server.example-vpn.tld
Endpoint = 37.156.147.42:56652
PublicKey =     #Paste PFsense Publickey to Ubuntu Peers
#aAllowedIPs = 0.0.0.0/0
AllowedIPs = 172.19.22.0/24
PersistentKeepalive = 25
