[Interface]
# Name = laptop.example-vpn.dev
Address = 172.19.24.2
PrivateKey = kM8iKPicfkRJqBSI8KwXjRx8gN5OXeHVlOZUBDr/smM=
#DNS = 1.1.1.1
ListenPort = 52244
[Peer]
# Name = server.example-vpn.tld
Endpoint = 37.156.147.42:56654
PublicKey = b+gtDLX7Wz+jaH+QQkYTldMpH7/SkgL1bV8mPKvYGDo=    #Paste PFsense Publickey to Ubuntu Peers
#aAllowedIPs = 0.0.0.0/0
AllowedIPs = 172.19.24.0/24
PersistentKeepalive = 25
