[Interface]
# Name = laptop.example-vpn.dev
Address = 172.19.23.2
PrivateKey = mDFl3NuMt/5DEPk/V6sxfOxRhPLyPMjGYABwJjLLPlU=
#DNS = 1.1.1.1
ListenPort = 52243
[Peer]
# Name = server.example-vpn.tld
Endpoint = 37.156.147.42:56653
PublicKey = KggA4PSDa/3cSMNauHI4v/one19J+Gcr7XEWo/W7/jQ=    #Paste PFsense Publickey to Ubuntu Peers
#aAllowedIPs = 0.0.0.0/0
AllowedIPs = 172.19.23.0/24
PersistentKeepalive = 25
