[Interface]
# Name = laptop.example-vpn.dev
Address = 172.18.1.2
PrivateKey = MNk8fkcCAlcewcIInkcDhVlY5lbGZLS+JE+1EqYQ/Vs=
#DNS = 1.1.1.1
ListenPort = 51438
[Peer]
# Name = server.example-vpn.tld
Endpoint = 37.152.190.80:54323
PublicKey = ESx+jdxnZ+rwfb2QAMls0BZubcUS+IB+E1hslw87MUs=    #Paste PFsense Publickey to Ubuntu Peers
#aAllowedIPs = 0.0.0.0/0
AllowedIPs = 172.18.1.0/24
PersistentKeepalive = 25
