[Interface]
# Name = laptop.example-vpn.dev
Address = 172.19.5.2
PrivateKey =OCjW8yFC2jSEOHF8BzyfbQlAEkHd66SeWoN5tFeqd0Y=
#DNS = 1.1.1.1
ListenPort = 52216
[Peer]
# Name = server.example-vpn.tld
Endpoint = 37.156.147.42:56626
PublicKey = ENjJvu0OIE+KvXNx77q6IVXqsmQbYcpHDA0Uboa/2kc=    #Paste PFsense Publickey to Ubuntu Peers
#aAllowedIPs = 0.0.0.0/0
AllowedIPs = 172.19.5.0/24
PersistentKeepalive = 25
