[Interface]
# Name = laptop.example-vpn.dev
Address = 172.19.1.2
PrivateKey = SGMRave/YsI61Ox8VJpMHCowRvlVurdzgLDjiBWqIVA=
#DNS = 1.1.1.1
ListenPort = 58236
[Peer]
# Name = server.example-vpn.tld
Endpoint = 37.156.147.42:54268
PublicKey = R7Kw+fBfEUdHuqeCR2D3voeWExC0ZTQUhsbttI0Ndzc=    #Paste PFsense Publickey to Ubuntu Peers
#aAllowedIPs = 0.0.0.0/0
AllowedIPs = 172.19.1.0/24
PersistentKeepalive = 25
