[Interface]
# Name = laptop.example-vpn.dev
Address = 172.19.3.2
PrivateKey = uHE1TADtyT01gTd7tDuT/koctEhIOUZbZSDr6/gzKVg=
#DNS = 1.1.1.1
ListenPort = 52214
[Peer]
# Name = server.example-vpn.tld
Endpoint = 37.156.147.42:56624
PublicKey = 3wbORb3SHXybuNDeS0Kqm/zPdpbuK6mpSbOR+eJEC1Y=    #Paste PFsense Publickey to Ubuntu Peers
#aAllowedIPs = 0.0.0.0/0
AllowedIPs = 172.19.3.0/24
PersistentKeepalive = 25
