[Interface]
# Name = laptop.example-vpn.dev
Address = 172.19.8.2
PrivateKey =kOeDx8KwT9pT6wwOSIKTfzJG2lJ6kW7FeNxLhNKQrWE=
#DNS = 1.1.1.1
ListenPort = 52219
[Peer]
# Name = server.example-vpn.tld
Endpoint = 37.156.147.42:56629
PublicKey = dc362ykPBrPafYE1h/mqUPbrNwc7k17O7fBAoxeYKgg=   #Paste PFsense Publickey to Ubuntu Peers
#aAllowedIPs = 0.0.0.0/0
AllowedIPs = 172.19.8.0/24
PersistentKeepalive = 25
